### ISSUE TITLE
Replace bash scripts for prebuild with TS for Windows support

### ISSUE THREAD

**Issue by ctrlc03** [privacy-ethereum/maci#1346]
Currently, MACI relies on some bash scripts for prebuild activities, removing these will open up being supported on Windows.

**Comment by samajammin** [comment]
Any thoughts on how to replace them?

**Comment by ctrlc03** [comment]
> Any thoughts on how to replace them?

we could simply re-write the logic in typescript. The bash scripts really only just run a sequence of typescript scripts so shouldn't be too much effort
