### ISSUE TITLE
Support maci deployment for apeworx

### ISSUE THREAD

**Issue by baumstern** [privacy-ethereum/maci#662]
apeworx is based on Python 
https://www.apeworx.io

**Comment by ctrlc03** [comment]
@baumstern was this requested by some community member that you know of?  is the framework still used now that foundry seems to be the main player with hardhat in second place?

**Comment by ctrlc03** [comment]
Closing this for now as there was no demand for it, but please feel free to re-open if there's any request for such integration. (would maybe be great to actually be able to support foundry but that sounds like a separate one)
